image: arbory/arbory:ci-php8.3-nodejs20

variables:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: test
    DB_HOST: mysql
    DB_DATABASE: test
    DB_USERNAME: root
    DB_PASSWORD: pass
    XDEBUG_MODE: coverage
    DEPLOY_REVISION: $CI_COMMIT_REF_SLUG:$CI_COMMIT_SHORT_SHA
    GOTENBERG_URL: $GOTENBERG_URL

.deploy: &deploy
    stage: deploy
    allow_failure: false
    needs: []
    tags:
        - deploy
    script:
    - npx --yes -p shell-deployer@1.6.5 deploy-laravel app.tgz --with-build
    - |
        eval $(ssh-agent -s)
        echo "$DEPLOY_SSH_PRIVATE_KEY" | ssh-add -
        mkdir -p ~/.ssh
        echo "$DEPLOY_SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        ssh $DEPLOY_USER@$DEPLOY_HOST "docker ps -q -f name=gotenberg | grep -q . || docker run -d --name gotenberg --restart unless-stopped -p 3000:3000 gotenberg/gotenberg:8"

stages:
    - deploy

deploy to staging:
    <<: *deploy
    when: manual
    environment:
        name: staging
        url: https://majas-receptes.cube.lv
    variables:
        DEPLOY_HOST: staging.cube.lv
        DEPLOY_USER: majas_receptes
        DEPLOY_PHP_COMMAND: php8.3
        DEPLOY_PATH: /home/majas_receptes/app
        DEPLOY_SSH_KNOWN_HOSTS: $AGENCY_STAGING_DEPLOY_KNOWN_HOSTS
        DEPLOY_SSH_PRIVATE_KEY: $AGENCY_STAGING_DEPLOY_PRIVATE_KEY
