/** @type {import('stylelint').Config} */
export default {
    ignoreFiles: [
        '**/app/**',
        '**/bootstrap/**',
        '**/build/**',
        '**/dist/**',
        '**/node_modules/**',
        '**/public/**',
        '**/routes/**',
        '**/storage/**',
        '**/tests/**',
        '**/vendor/**',
        '**/packages/**',
        '**/*.min.css',
    ],

    customSyntax: 'postcss-scss',
    extends: ['stylelint-config-standard-scss'],
    overrides: [
        {
            files: ['resources/assets/scss/**/*.scss'],
            customSyntax: 'postcss-scss',
        },
    ],

    rules: {
        'at-rule-empty-line-before': null,
        'at-rule-no-unknown': null,
        'block-no-empty': true,
        'color-hex-length': 'long',
        'color-no-invalid-hex': true,
        'declaration-empty-line-before': null,
        'max-nesting-depth': [5, { ignore: ['blockless-at-rules', 'pseudo-classes'] }],
        'no-descending-specificity': null,
        'no-duplicate-selectors': true,
        'number-max-precision': 5,
        'scss/at-rule-no-unknown': true,
        'scss/comment-no-empty': null,
        'scss/dollar-variable-empty-line-before': null,
        'scss/no-global-function-names': null,
        'scss/operator-no-newline-after': null,
        'scss/operator-no-unspaced': null,
        'selector-class-pattern': '^([a-z][a-z0-9]*)(-[a-z0-9]+)*$',
        'selector-max-id': 0,
        'media-feature-range-notation': 'prefix',
        'alpha-value-notation': null,
        'selector-pseudo-element-colon-notation': 'single',
        'rule-empty-line-before': [
            'always',
            {
                except: ['first-nested'],
                ignore: ['after-comment'],
            },
        ],
        'unit-no-unknown': [true, { ignoreUnits: ['steps'] }],
        'import-notation': null,
        'font-family-name-quotes': 'always-unless-keyword',
        'value-keyword-case': [
            'lower',
            {
                ignoreKeywords: ['currentColor', 'optimizeQuality'],
            },
        ],
        'unit-allowed-list': [
            '%',
            'px',
            'rem',
            'em',
            'vh',
            'vw',
            'dvw',
            'dvh',
            'deg',
            's',
            'ms',
            'fr',
            'ch',
            'vmin',
            'vmax',
            'dppx',
        ],
    },

    reportNeedlessDisables: true,
    reportInvalidScopeDisables: true,
};
